url: http://mlnotes.com
baseurl: /blog
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "Machine Learning Notes"
markdown: rdiscount
author: hanfeng
email: zhuhanfeng@gmail.com
